### PR TITLE
feat: update to 2024b IANA db

### LINKED ISSUE #62: Wrong utcOffset for Dublin
Thanks for this module! Trying to use it and the very first example I used was Dublin, but the answer looks wrong.

```js
ct.getTimezone('Europe/Dublin')
```

yields:

```js
{
    name: 'Europe/Dublin',
    countries: [ 'IE' ],
    utcOffset: 60,
    utcOffsetStr: '+01:00',
    dstOffset: 0,
    dstOffsetStr: '+00:00',
    aliasOf: null
}
```

The [UTC for Dublin is 0](https://www.zeitverschiebung.net/en/timezone/europe--dublin), whereas the DST can be +1.

### LINKED ISSUE #66: Asia/Almaty timezone is outdated (old IANA db)
Timezone for Asia/Almaty right now is +5 GMT, while in current release it is +6 GMT.
It's fixed in 2024a release of IANA db.

### PR DESCRIPTION
**Pull request by jcfranco**
Update tz db according to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.

Fixes #62
Fixes #66

### CODE REVIEW

**Comment by jcfranco** [comment]
@manuelmhtr This is based on https://github.com/manuelmhtr/countries-and-timezones/commit/653e28b0024ebb6fb6ce96ccd615c847e2ba332d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5. LMK if you'd like or need me to make any adjustments.

**Comment by jcfranco** [comment]
@manuelmhtr WDYT about updating just the data and test files in this PR, and handling the remaining updates separately as part of a release? I think this could help keep the changes more focused.

**Comment by manuelmhtr** [comment]
@jcfranco no worries, it's perfect. Just please update `package.json` version so I can publish the new version in NPM.

**Review by manuelmhtr — APPROVED** [review]

**Comment by jcfranco** [comment]
Done!

**Comment by jcfranco** [comment]
If you'd like to only keep the conventional commit, you can squash merge this PR.

**Comment by manuelmhtr** [comment]
Merged. Thank you!

**Pull request closed without merging**
